### ISSUE TITLE
Tool Information Image Error

### ISSUE THREAD

**Issue by SMXaS** [kvarcas91/Shared-Power#12]
Search Tool Page ----> Select a Tool ----> Tool Information ---> Show Image --->Either you press--->Hire Tool or --->Go back.
 The Image is still not closing. 
You can select after that again another tool and show the picture, which will open multiple images.
F.E Select Shoe ---> Go to Tool Information and show Image--->Go back and select Amazon Locker --->Go to Tool Information and Show image, you can go back and do it again or you can hire a tool and image will still be there.

**Comment by kvarcas91** [comment]
fixed
