### ISSUE TITLE
Hiretool

### ISSUE THREAD

**Issue by greatdorcas** [kvarcas91/Shared-Power#13]
Search tool------ Corded nailer ----- Hire tool: 11/01/19 hire tool has the same return date. While other dates has up to three days for registered user to return the tool.

**Comment by kvarcas91** [comment]
It does not show these days because this tool is already booked for 12th - 14th days

**Comment by kvarcas91** [comment]
![capture](https://user-images.githubusercontent.com/27624369/51020222-daef8d00-1575-11e9-926b-b2defb6c5c22.JPG)
