### ISSUE TITLE
My Bookings

### ISSUE THREAD

**Issue by greatdorcas** [kvarcas91/Shared-Power#14]
After hiring a too,l in order to see what i hired. I need to check My Bookings but i can not find the tool i hired in My Bookings

**Comment by kvarcas91** [comment]
please provide pictures of console log, which tool you are trying to book and yourBooking page

**Comment by kvarcas91** [comment]
Please do not add not code related files into code section. You can upload files here by dragging images to text field. Please provide pictures of every step you did, every button you pressed and also if there was any error in the console log

**Comment by kvarcas91** [comment]
Incorrectly imported project. Resolving
