### ISSUE TITLE
Return Tool Bug

### ISSUE THREAD

**Issue by SMXaS** [kvarcas91/Shared-Power#15]
If You Press on Return Tool and it Asks to Provide Condition, You Can Press Cancel Booking too, Pressing Yes, Will Leave 'Provide Condition' So You Can Write Anything and Confirm it

**Comment by kvarcas91** [comment]
Do you use the newest version? because it doesn't show provide condition and Confirm labels after you press Cancel or Confirm

**Comment by kvarcas91** [comment]
Resolving as there are no further comments from the requester.
