### ISSUE TITLE
Shared Power Create Account

### ISSUE THREAD

**Issue by greatdorcas** [kvarcas91/Shared-Power#5]
At the __main__.py when i run the code, the dialog box pops up. We need to add Forget password(we should include Email, new password and password confirmation).

When i inserted my details on the dialog box, I clicked CREATE ACCOUNT it says that "some

 fields contain spaces".

**Comment by kvarcas91** [comment]
It throws that error because we cannot place space in post code field. I.e. instead of writing "lu1 5hp", remove space and write "lu15hp". The reason behind this is that I wanted to prevent from users ignoring this field (leaving emtpy) or just putting space (" ")

**Comment by kvarcas91** [comment]
There is no further plans for resetting password, because it will need to send an email for it. And we do not use internet access for our app

**Comment by greatdorcas** [comment]
Add currency before the price per Day and Price per Half Day

**Comment by greatdorcas** [comment]
Please change currency position.  can you please arrange the text on tool information, it is not well arrange thank you

**Comment by kvarcas91** [comment]
New problem - new issue. Dont put everything here. What do you mean by arranging text information in toolInfoPage? How it should be arranged then?

**Comment by greatdorcas** [comment]
Why is the price fixed for both Full day and Half day?n  ]

**Comment by kvarcas91** [comment]
Done with Registration page Issue where user wasn't allow to register if enters post code with space inside
