### ISSUE TITLE
Delete tool button

### ISSUE THREAD

**Issue by greatdorcas** [kvarcas91/Shared-Power#6]
Hi guys, delete tool ~~and damage/restore button~~ is not working

~~At the total cost can you please change the currency behind the value.~~

~~If the registered user don't want to book a rider, please make it easy so it will be possible to click on ARRANGE RIDER~~

~~Returning a tool late is fined at double the day rate for every day it is missing is not included guys~~

**Comment by greatdorcas** [comment]
Please add it up

**Comment by kvarcas91** [comment]
Why do you think and how did you "find" that late return is not calculated?

**Comment by kvarcas91** [comment]
Change availability button works.
Placed currency value after the number
Replaced Arrange Rider RadioButton with CheckBox

**Comment by Gilmir** [comment]
Delete button work now.
