### ISSUE TITLE
position

### ISSUE THREAD

**Issue by greatdorcas** [kvarcas91/Shared-Power#8]
Change the position of return item and cancel booking

**Comment by kvarcas91** [comment]
1. Why do we need to change?
2. What impact it will give?
3. Can you please propose your way how do you imagine these changes?

**Comment by greatdorcas** [comment]
Is it okay if you insert it below instead of leaving it at the top left or do you want to add more buttons?

**Comment by kvarcas91** [comment]
1. Why do we need to change it?
2. What impact it will give?

**Comment by kvarcas91** [comment]
Done
